using System;
using System.Collections.Generic;
using System.Text;

namespace Yort.Eftpos.Verifone.PosLink
{
	/// <summary>
	/// Specifies where a display message was generated.
	/// </summary>
	public enum DisplayMessageSource
	{
		/// <summary>
		/// The display message was generated by the Yort.Eftpos.Verifone.PosLink library code.
		/// </summary>
		Library = 0,
		/// <summary>
		/// The display message came from the pin pad.
		/// </summary>
		Pinpad
	}
}